POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "usernameOrEmail": "jgomez4444@mail.com",
  "password": "Password123"
}

> {% client.global.set("auth_token", response.body.accessToken); %}
###

POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "firstName": "Juan",
  "lastName": "Gomez",
  "username": "jgomez123",
  "email": "jgomez4444@mail.com",
  "password": "Password123"
}