### get posts

GET http://localhost:8080/posts

### get post

GET http://localhost:8080/posts/1

### get Categories post

GET http://localhost:8080/posts/categories

### get post tags

GET http://localhost:8080/posts/tag

### create Post
#for create post is necesari List tasg, current user, valid categories.

POST http://localhost:8080/posts
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "categories": [
    {
      "id": "1",
      "key": "1"
    }
  ],
  "content": "You're joking. You're joking! I can't believe my eyes!",
  "description": "Omg you guys look :D",
  "image": "https://imgur.com/gallery/sSHnm",
  "name": "jimmySteve1",
  "tags": [
    {
      "id": "1",
      "name": "tag1"
    }
  ],
  "title": ":D ",
  "type": "rest",
  "urlStorage": "https://vladmihalcea.com/hibernate-multiplebagfetchexception/"
}

### get unaproved posts
GET http://localhost:8080/posts/unapproved
Authorization: Bearer {{auth_token}}

### aprove post
POST http://localhost:8080/posts/approve/12
Authorization: Bearer {{auth_token}}